# Generated by Django 3.2.25 on 2025-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_charity_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycontact',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
