# Generated by Django 3.2.25 on 2025-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_charitycontact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitydonation',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
