# Generated by Django 3.2.25 on 2025-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charitydonation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
