# Generated by Django 3.2.25 on 2025-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_charity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='overview',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='charitycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='charitycontact',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
