# Generated by Django 3.2.25 on 2025-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(default='unknown', max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
