# Generated by Django 3.2.25 on 2025-09-01 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_loginout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
