# Generated by Django 3.2.25 on 2026-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_loginout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginout',
            name='importance',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='loginout',
            name='type',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
