# Generated by Django 4.2.28 on 2026-03-31 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20260210_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(default=0)),
                ('club_name', models.CharField(max_length=100)),
                ('club_link', models.URLField(default=None)),
                ('secretary_name', models.CharField(max_length=100)),
                ('secretary_telephone', models.CharField(max_length=15)),
                ('secretary_email', models.EmailField(default=None, max_length=254)),
                ('meeting_location', models.CharField(max_length=100)),
                ('meeting_time', models.TimeField(default=datetime.time(18, 30))),
                ('reminder_1_days', models.IntegerField(default=13)),
                ('reminder_2_days', models.IntegerField(default=8)),
                ('attendance_change_days', models.IntegerField(default=6)),
            ],
        ),
    ]
