# Generated by Django 4.2.28 on 2026-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_clubdefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdefaults',
            name='secretary_position',
            field=models.CharField(default='Meeting Secretary', max_length=100),
            preserve_default=False,
        ),
    ]
