# Generated by Django 4.2.28 on 2026-04-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_clubdefaults_secretary_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogInOut',
        ),
    ]
