# Generated by Django 4.2.28 on 2026-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_loginout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdefaults',
            name='club_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='meeting_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
