# Generated by Django 4.2.28 on 2026-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_clubdefaults_club_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdefaults',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clubdefaults',
            name='secretary_telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
