# Generated by Django 4.2.28 on 2026-03-20 17:05

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='Beer Cafe, Bury St Edmunds', max_length=100)),
                ('meeting_time', models.TimeField(default=datetime.time(18, 30))),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=django.contrib.auth.models.User)),
                ('username', models.CharField(blank=True, max_length=60)),
                ('dietary_requirements', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.IntegerField(default=django.contrib.auth.models.User)),
                ('guest_name', models.CharField(max_length=60)),
                ('guest_dr', models.CharField(blank=True, max_length=60)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.businessmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField(default=django.contrib.auth.models.User)),
                ('attending', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.businessmeeting')),
            ],
        ),
    ]
