# Generated by Django 4.2.28 on 2026-03-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                   ALTER TABLE reports_businessmeeting
                   ADD COLUMN location varchar(100) NOT NULL
                   DEFAULT 'Beer Cafe, Bury St Edmunds';
               """,
            reverse_sql="""
                   ALTER TABLE reports_businessmeeting
                   DROP COLUMN location;
               """,
        ),
    ]
