# Generated by Django 4.2.28 on 2026-03-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_location_column_fix'),
        ('reports', '0003_add_meeting_time_column'),
    ]

    operations = [
    ]
