# Generated by Django 4.2.28 on 2026-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_merge_20260320_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmeeting',
            name='date',
            field=models.DateField(),
        ),
    ]
