# Generated by Django 4.2.28 on 2026-04-18 16:31

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_businessmeeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmeeting',
            name='first_email',
            field=models.IntegerField(default=reports.models.get_default_reminder_1),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='last_change_date',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('S', 'Social Meeting'), ('M', 'Business Meeting')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='second_email',
            field=models.IntegerField(default=reports.models.get_default_reminder_2),
        ),
        migrations.AlterField(
            model_name='businessmeeting',
            name='location',
            field=models.CharField(default='Green King, Beer Cafe, Bury St Edmunds', max_length=100),
        ),
    ]
