# Generated by Django 4.2.28 on 2026-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_businessmeeting_first_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmeeting',
            name='meeting_title',
            field=models.CharField(default='Business Meeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('S', 'Social Meeting'), ('M', 'Business Meeting')], default='M', max_length=1),
        ),
    ]
