# Generated by Django 4.2.28 on 2026-06-08 09:10

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_businessmeeting_meeting_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmeeting',
            name='organiser_email',
            field=models.EmailField(blank=True, default=reports.models.get_default_organiser_email, max_length=254),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='organiser_name',
            field=models.CharField(blank=True, default=reports.models.get_default_organiser_name, max_length=100),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='organiser_position',
            field=models.CharField(blank=True, default=reports.models.get_default_organiser_position, max_length=100),
        ),
        migrations.AddField(
            model_name='businessmeeting',
            name='organiser_telephone',
            field=models.CharField(blank=True, default=reports.models.get_default_organiser_telephone, max_length=15),
        ),
        migrations.AlterField(
            model_name='businessmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('Social', 'Social Meeting'), ('Meeting', 'Business Meeting')], default='Meeting', max_length=10),
        ),
    ]
