# Generated by Django 3.2.25 on 2025-04-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_auto_20250414_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crm',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.company'),
        ),
    ]
