# Generated by Django 3.2.25 on 2025-09-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companys', '0005_auto_20250414_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crm',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
