# Generated by Django 3.2.25 on 2026-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0006_auto_20250911_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='emailconsent',
            field=models.BooleanField(default=True),
        ),
    ]
