# Generated by Django 3.2.25 on 2025-07-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotedate',
            new_name='meetingdate',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='position',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoteprice',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sitestatus',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='web',
        ),
        migrations.AddField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('Mins', 'Meeting Minutes'), ('Agds', 'Meeting Agenda'), ('Acc', 'Accounts'), ('Com_Reps', 'Committee Reports'), ('Oth', 'Other')], default='Oth', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
