# Generated by Django 3.2.25 on 2025-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20250701_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='jobfile',
            field=models.FileField(blank=True, upload_to='barc_root/uploads/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('Minutes', 'Meeting Minutes'), ('Agenda', 'Meeting Agenda'), ('Accounts', 'Accounts'), ('CommitteeReports', 'Committee Reports'), ('Social', 'Scocial Events'), ('Car Show', 'Car Show Documents'), ("St Ed's Dinner", "St Ed's Dinner Documents"), ('Golf Day', 'Golf Day Documents'), ('Auction', 'Auction Documents'), ('Press', 'Press Releases'), ('Logos', 'Company Logos'), ('Other', 'Other')], default='Oth', max_length=20),
        ),
    ]
