# Generated by Django 4.2.28 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20260205_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('Minutes', 'Meeting Minutes'), ('Agenda', 'Meeting Agenda'), ('Council Minutes', 'Council Meeting Minutes'), ('Council Agenda', 'Council Meeting Agenda'), ('Accounts', 'Accounts'), ('CommitteeReports', 'Committee Reports'), ('Social', 'Scocial Events'), ('Car Show', 'Car Show Documents'), ("St Ed's Dinner", "St Ed's Dinner Documents"), ('Golf Day', 'Golf Day Documents'), ('Auction', 'Auction Documents'), ('Press', 'Press Releases'), ('Logos', 'Company Logos'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
